service_whitelist: 
  ["/change_map",
  "/foxglove_bridge/get_loggers",
  "/foxglove_bridge/set_logger_level",
  "/foxglove_nodelet_manager/get_loggers",
  "/foxglove_nodelet_manager/list",
  "/foxglove_nodelet_manager/load_nodelet",
  "/foxglove_nodelet_manager/set_logger_level",
  "/foxglove_nodelet_manager/unload_nodelet",
  "/get_all_maps",
  "/get_current_map",
  "/global_localization/get_loggers",
  "/global_localization/set_logger_level",
  "/laserMapping/get_loggers",
  "/laserMapping/set_logger_level",
  "/livox_lidar_publisher2/get_loggers",
  "/livox_lidar_publisher2/set_logger_level",
  "/load_map",
  "/map_manager/get_loggers",
  "/map_manager/set_logger_level",
  "/map_manager/tf2_frames",
  "/map_server_1751004889985711984/get_loggers",
  "/map_server_1751004889985711984/set_logger_level",
  "/move_base/GlobalPlanner/make_plan",
  "/move_base/GlobalPlanner/set_parameters",
  "/move_base/clear_costmaps",
  "/move_base/get_loggers",
  "/move_base/global_costmap/inflation_layer/set_parameters",
  "/move_base/global_costmap/set_parameters",
  "/move_base/global_costmap/static_layer/set_parameters",
  "/move_base/local_costmap/inflation_layer/set_parameters",
  "/move_base/local_costmap/set_parameters",
  "/move_base/local_costmap/static_layer/set_parameters",
  "/move_base/make_plan",
  "/move_base/set_logger_level",
  "/move_base/set_parameters",
  "/navigate_to_task_point",
  "/pcd_to_pointcloud/get_loggers",
  "/pcd_to_pointcloud/set_logger_level",
  "/pointcloud_to_laserscan/get_loggers",
  "/pointcloud_to_laserscan/list",
  "/pointcloud_to_laserscan/load_nodelet",
  "/pointcloud_to_laserscan/set_logger_level",
  "/pointcloud_to_laserscan/unload_nodelet",
  "/rosout/get_loggers",
  "/rosout/set_logger_level",
  "/static_map",
  "/static_transform_publisher/get_loggers",
  "/static_transform_publisher/set_logger_level",
  "/task_point"
  ]
