// Generated by gencpp from file hardware_node/horizontalMotionByStep.msg
// DO NOT EDIT!


#ifndef HARDWARE_NODE_MESSAGE_HORIZONTALMOTIONBYSTEP_H
#define HARDWARE_NODE_MESSAGE_HORIZONTALMOTIONBYSTEP_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace hardware_node
{
template <class ContainerAllocator>
struct horizontalMotionByStep_
{
  typedef horizontalMotionByStep_<ContainerAllocator> Type;

  horizontalMotionByStep_()
    : step(0)  {
    }
  horizontalMotionByStep_(const ContainerAllocator& _alloc)
    : step(0)  {
  (void)_alloc;
    }



   typedef int32_t _step_type;
  _step_type step;





  typedef boost::shared_ptr< ::hardware_node::horizontalMotionByStep_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::hardware_node::horizontalMotionByStep_<ContainerAllocator> const> ConstPtr;

}; // struct horizontalMotionByStep_

typedef ::hardware_node::horizontalMotionByStep_<std::allocator<void> > horizontalMotionByStep;

typedef boost::shared_ptr< ::hardware_node::horizontalMotionByStep > horizontalMotionByStepPtr;
typedef boost::shared_ptr< ::hardware_node::horizontalMotionByStep const> horizontalMotionByStepConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::hardware_node::horizontalMotionByStep_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::hardware_node::horizontalMotionByStep_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::hardware_node::horizontalMotionByStep_<ContainerAllocator1> & lhs, const ::hardware_node::horizontalMotionByStep_<ContainerAllocator2> & rhs)
{
  return lhs.step == rhs.step;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::hardware_node::horizontalMotionByStep_<ContainerAllocator1> & lhs, const ::hardware_node::horizontalMotionByStep_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace hardware_node

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::hardware_node::horizontalMotionByStep_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::hardware_node::horizontalMotionByStep_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::hardware_node::horizontalMotionByStep_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::hardware_node::horizontalMotionByStep_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::hardware_node::horizontalMotionByStep_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::hardware_node::horizontalMotionByStep_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::hardware_node::horizontalMotionByStep_<ContainerAllocator> >
{
  static const char* value()
  {
    return "99174260c0c07917ce2b7a46302ab7a8";
  }

  static const char* value(const ::hardware_node::horizontalMotionByStep_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x99174260c0c07917ULL;
  static const uint64_t static_value2 = 0xce2b7a46302ab7a8ULL;
};

template<class ContainerAllocator>
struct DataType< ::hardware_node::horizontalMotionByStep_<ContainerAllocator> >
{
  static const char* value()
  {
    return "hardware_node/horizontalMotionByStep";
  }

  static const char* value(const ::hardware_node::horizontalMotionByStep_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::hardware_node::horizontalMotionByStep_<ContainerAllocator> >
{
  static const char* value()
  {
    return "# 单步左右转动，传入值为转动的步长\n"
"int32 step\n"
;
  }

  static const char* value(const ::hardware_node::horizontalMotionByStep_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::hardware_node::horizontalMotionByStep_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.step);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct horizontalMotionByStep_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::hardware_node::horizontalMotionByStep_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::hardware_node::horizontalMotionByStep_<ContainerAllocator>& v)
  {
    s << indent << "step: ";
    Printer<int32_t>::stream(s, indent + "  ", v.step);
  }
};

} // namespace message_operations
} // namespace ros

#endif // HARDWARE_NODE_MESSAGE_HORIZONTALMOTIONBYSTEP_H
